title: KeenCoder.dev
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keencoder.dev/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Srinivasa Rao # add your name
author-img: avatar.jpeg # add your photo
about-author: I am a software developer, I love building things with Python and JavaScript. # add description
social-twitter: Srinandan33 # add your Twitter handle
social-facebook: ""
social-github: sriNandan33 # add your Github handle
social-linkedin: srinivas33 # add your Linkedin handle
social-email: nandusrinivas33.cse@gmail.com # add your Email address

# Disqus
discus-identifier: keencoder-dev # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 7
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
